### PR TITLE
Bump nexus to 3.37.3-02

### PR DESCRIPTION
**Pull request by DmitriyStoyanov**
See Release notes here: https://help.sonatype.com/repomanager3/product-information/release-notes/2021-release-notes/nexus-repository-3.37.0---3.37.3-release-notes

### CODE REVIEW

**Comment by DmitriyStoyanov** [comment]
also builded new image for testing purposes `scorpio2002/nexus:3.37.3`

**Comment by DmitriyStoyanov** [comment]
Tested on our nexus instance, all looks good
New temporary feature "Log4j Visualizer" works fine
https://help.sonatype.com/repomanager3/nexus-repository-administration/capabilities/log4j-visualizer
Enabled via Server Administration and Configuration -> System-> Capabilities

**Review by bpietraga — APPROVED** [review]
Great, thank you!

**Comment by DmitriyStoyanov** [comment]
It is interesting, image build in quay.io still cannot be done
https://quay.io/repository/travelaudience/docker-nexus?tab=info
image

And latest image here: https://quay.io/repository/travelaudience/docker-nexus?tab=tags
is `3.37.1-01`

Possibly better to create github workflow to build image on github on every change for test purposes and push it to image registry with specific tag from git tags and with latest tag from master branch?

For example https://github.com/marketplace/actions/push-to-registry#examples

**Comment by DmitriyStoyanov** [comment]
As I see, image appears in quay.io, so added MR here: Oteemo/charts#325 to bump version there also

**Pull request merged**
