### PR TITLE
Upgrade to Nexus 3.19.0

### LINKED ISSUE #28: Upgrade to Nexus 3.19.0

### PR DESCRIPTION
**Pull request by PG2000**
Closes #28

### CODE REVIEW

**Comment by PG2000** [comment]
@arochaf @TAvardit any chance to merge this?

**Comment by TAvardit** [comment]
@PG2000 This looks good but we will need to test it before merge so it will take a bit of time before a merge.

**Comment by PG2000** [comment]
> @PG2000 This looks good but we will need to test it before we can merge it.

Is there anything I can help with?

**Comment by cingaldi** [comment]
Hello, Thank you @PG2000 

My team is interested to test it

**Comment by luigicaiffa** [comment]
> @PG2000 This looks good but we will need to test it before we can merge it.

Any problems with the tests?
This pull request solves the problem on the npm repository that is currently not working for version 3.17.
@TAvardit  can I help you in any way?

**Comment by xpicio** [comment]
@arochaf @TAvardit any news about this update ?

**Comment by TAvardit** [comment]
Hi @PG2000 @xpicio @luigicaiffa @cingaldi,
I took PG200 PR and bump the version to `3.19.1` on the way. I tested the version and everything seems stable. I couldn't do it on this PR so I opened a new one based on this one:
https://github.com/travelaudience/docker-nexus/pull/31
It will be soon merged and built.

**Pull request closed without merging**
