### PR TITLE
Select nexus version

### PR DESCRIPTION
**Pull request by jmartinezfl**
Add the option to pass the nexus version as an argument

### CODE REVIEW

**Comment by jeff-knurek** [comment]
Hi @jmartinezfl 
Can you provide some more info into the use case for this? Because my understanding is that the `ARG` value would only be used during build time, and as there's only the one build, there's no need to make it a variable.

**Comment by jmartinezfl** [comment]
I think it is useful in cases of automatic construction of the image. So you don't have to modify the Dockerfile every time you want to change the version.
Modifying the file is not a complicated task, but the option to parameterize the version seemed more interesting and flexible.

**Comment by jeff-knurek** [comment]
Ok, that makes sense. 
But we're using quay.io and the build trigger is on the github tag. Based on this issue, I don't think it's possible to take advantage of this strategy: https://github.com/coreos/quay-docs/issues/62

**Comment by cmoroianu1** [comment]
In our build environment this won't work. I'll close the PR. Feel free to fork and use in your environment if this is really needed for your use case.

**Pull request closed without merging**
