### PR TITLE
Update OpenJDK, Alpine and Nexus to 3.17.0

### PR DESCRIPTION
**Pull request by TAvardit**

### CODE REVIEW

**Comment by pires** [comment]
I suggest next time you look into open PRs to see if you're not throwing other people's contributions away, such as #19, which already partially addresses what was done here.

**Comment by pires** [comment]
This also fixed #18. Please, you are now the maintainers of this so pay attention to this so that a community can grow around it.

**Comment by pires** [comment]
cc @arochaf

**Comment by jansmets** [comment]
And meanwhile 3.18.0 is out. :-)

**Pull request merged**
