### PR TITLE
Bump nexus to 3.37.1 version

### PR DESCRIPTION
**Pull request by DmitriyStoyanov**
See release notes in https://help.sonatype.com/repomanager3/product-information/release-notes/2021-release-notes/nexus-repository-3.37.0---3.37.1-release-notes

### CODE REVIEW

**Comment by DmitriyStoyanov** [comment]
Published in image `scorpio2002/nexus:3.37.1` and tested locally, all works fine

**Comment by DmitriyStoyanov** [comment]
to test you can run it like `docker run -p 8081:8081 --name nexus scorpio2002/nexus:3.37.1`

**Review by bpietraga — APPROVED** [review]
Thanks @DmitriyStoyanov! I really appreciate your work.

**Comment by DmitriyStoyanov** [comment]
By the way, new release should be created with tag and new image `quay.io/travelaudience/docker-nexus:3.37.1-01` in https://quay.io/repository/travelaudience/docker-nexus?tag=latest&tab=tags there are only 3.36.0-01 latest image
and in docs we have info about new image, but this image doesn't exist

**Comment by cmoroianu1** [comment]
Thank you Dmitry, new release published: https://github.com/travelaudience/docker-nexus/tree/3.37.1-01

**Comment by DmitriyStoyanov** [comment]
hm, but looks like here we still not have new image :( https://quay.io/repository/travelaudience/docker-nexus?tab=tags

By the way, possibly we can add github actions to publish new images with new tag creation? In that case this part will be automated if currently it is manual action.

**Pull request merged**
