### PR TITLE
Bump Nexus to 3.16.2-01, JDK to AdoptOpenJDK 8u212

### PR DESCRIPTION
**Pull request by mimatn**
Bumped to latest Nexus to date. Switched JDK base to AdoptOpenJDK 8u212 on Alpine slim.
Builds and starts locally: any other tests I should do?

Thank you in advance.

### CODE REVIEW

**Comment by irons** [comment]
What motivated the change of base image?

**Comment by mimatn** [comment]
Well, the previous image source is out of my reach and doesn't have a clean upgrade timeline. I thought that the official AdoptOpenJDK is similar enough. Moreover, if I recall correctly there are a few high profile security fixes in 8u212 that make it a recommended upgrade, especially for servers.
Do you suggest to keep the base current base image, and just upgrade the application?

**Comment by denis111** [comment]
Why not to use just official OpenJDK base image? I think it also uses AdoptOpenJDK recently https://github.com/docker-library/openjdk/commit/3eb0351b208d739fac35345c85e3c6237c2114ec#diff-c338262eaf0fd203322a06702be174e0

**Comment by mimatn** [comment]
> Why not to use just official OpenJDK base image?
> No alpine but at least slim variant...

That's Docker's "official", non OpenJDK's. I think the original focus on Alpine here is to drive the total image size down; current final image size is [below 200M](https://quay.io/repository/travelaudience/docker-nexus?tab=tags) while starting from debian stretch slim you already are over 400MB just for the base JDK.

**Comment by jansmets** [comment]
Regardless of the JDK, could we move ahead with the nexus version bump? There are some security updates.

**Comment by mimatn** [comment]
Worse than that, we have an even newer version, but with a quite different admin auth method. It would need testing time that I don't have right now.

**Comment by pires** [comment]
I am very sorry, but this PR was overlooked and #21 was created and merged. You can find the new release here https://github.com/travelaudience/docker-nexus/releases/tag/3.17.0.

Thank you very much for your contribution, and one more, I am sorry.

**Comment by mimatn** [comment]
Nevermind. The other PR is even better. Thank you.

**Pull request closed without merging**
